# Generated by Django 5.0.6 on 2024-07-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('representante', models.CharField(max_length=100)),
                ('id_tutor_empresarial', models.IntegerField()),
            ],
        ),
    ]
