# Generated by Django 5.0.6 on 2024-08-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_perfil_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cedula',
        ),
    ]
