# Generated by Django 5.0.6 on 2024-08-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_perfil_estado_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estado_carta_aprobacion',
            field=models.CharField(default='Espera', max_length=20),
        ),
    ]
