# Generated by Django 5.0.6 on 2024-08-05 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0008_perfil_estado_carta_aprobacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaAceptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('ano_lectivo', models.CharField(max_length=10)),
                ('fecha_subida', models.DateField()),
                ('comentarios_rector', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.formato')),
            ],
        ),
    ]
