# Generated by Django 5.0.6 on 2024-08-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_cartaaceptacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartaaceptacion',
            old_name='ano_lectivo',
            new_name='ano_lectivo_carta',
        ),
        migrations.RenameField(
            model_name='cartaaceptacion',
            old_name='cedula',
            new_name='cedula_carta',
        ),
        migrations.RenameField(
            model_name='cartaaceptacion',
            old_name='comentarios_rector',
            new_name='comentarios_rector_carta',
        ),
        migrations.RenameField(
            model_name='cartaaceptacion',
            old_name='estudiante',
            new_name='estudiante_carta',
        ),
        migrations.RenameField(
            model_name='cartaaceptacion',
            old_name='fecha_subida',
            new_name='fecha_subida_carta',
        ),
        migrations.AddField(
            model_name='cartaaceptacion',
            name='estado_carta',
            field=models.TextField(default='Espera'),
        ),
    ]
