# Generated by Django 5.0.6 on 2024-08-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0012_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='experiencia',
            field=models.TextField(max_length=500),
        ),
    ]
