# Generated by Django 5.0.6 on 2024-08-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0013_alter_tutor_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='estado_carta_aprobacion',
            field=models.CharField(default='Espera1', max_length=20),
        ),
    ]
