# Generated by Django 5.0.6 on 2024-08-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0014_alter_perfil_estado_carta_aprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaaceptacion',
            name='estado_carta',
            field=models.TextField(default='Espera1'),
        ),
    ]
