# Generated by Django 5.0.6 on 2024-08-08 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0015_alter_cartaaceptacion_estado_carta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tutor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil', to='estudiantes.tutor'),
        ),
    ]
