# Generated by Django 5.0.6 on 2024-08-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0016_perfil_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tutor_asignado_estado',
            field=models.CharField(default='Espera1', max_length=20),
        ),
    ]
