# Generated by Django 5.0.6 on 2024-08-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0017_perfil_tutor_asignado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ia_respuesta',
            field=models.CharField(default='Sin Respuesta', max_length=500),
        ),
    ]
