# Generated by Django 5.0.6 on 2024-08-09 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0018_perfil_ia_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='estudiantes.tutor'),
        ),
    ]
