# Generated by Django 5.0.6 on 2024-08-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0019_alter_perfil_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ia_estado',
            field=models.CharField(default='Espera', max_length=20),
        ),
    ]
