# Generated by Django 5.0.6 on 2024-08-10 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0020_perfil_ia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='empresa_estado',
            field=models.CharField(default='Espera', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='empresa_nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.empresa'),
        ),
    ]
