# Generated by Django 5.0.6 on 2024-08-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0021_perfil_empresa_estado_perfil_empresa_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='id_tutor_empresarial',
            field=models.CharField(max_length=100),
        ),
    ]
