# Generated by Django 5.0.6 on 2024-08-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0022_alter_empresa_id_tutor_empresarial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='id_tutor_empresarial',
            new_name='supervisor',
        ),
    ]
