# Generated by Django 5.0.6 on 2024-08-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0023_rename_id_tutor_empresarial_empresa_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='tutor_asignado_estado',
            new_name='supervisor',
        ),
    ]
