# Generated by Django 5.0.6 on 2024-08-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0024_rename_tutor_asignado_estado_perfil_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tutor_asignado_estado',
            field=models.CharField(default='Espera', max_length=20),
        ),
    ]
