# Generated by Django 5.0.6 on 2024-08-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0025_perfil_tutor_asignado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaaceptacion',
            name='empresa',
            field=models.CharField(default='Espera', max_length=100),
        ),
        migrations.AddField(
            model_name='cartaaceptacion',
            name='supervisor',
            field=models.CharField(default='Espera', max_length=100),
        ),
    ]
