# Generated by Django 5.0.6 on 2024-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0026_cartaaceptacion_empresa_cartaaceptacion_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(blank=True, max_length=255)),
                ('receptora', models.CharField(max_length=255)),
                ('nombre_estudiante', models.CharField(blank=True, max_length=255)),
                ('nombre_docente', models.CharField(blank=True, max_length=255)),
                ('area_trabajo', models.CharField(max_length=255)),
                ('fecha_semanal', models.DateField()),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('lunes_actividad', models.TextField()),
                ('lunes_dificultad', models.TextField()),
                ('lunes_apoyo', models.TextField()),
                ('lunes_observaciones', models.TextField()),
                ('martes_actividad', models.TextField()),
                ('martes_dificultad', models.TextField()),
                ('martes_apoyo', models.TextField()),
                ('martes_observaciones', models.TextField()),
                ('miercoles_actividad', models.TextField()),
                ('miercoles_dificultad', models.TextField()),
                ('miercoles_apoyo', models.TextField()),
                ('miercoles_observaciones', models.TextField()),
                ('jueves_actividad', models.TextField()),
                ('jueves_dificultad', models.TextField()),
                ('jueves_apoyo', models.TextField()),
                ('jueves_observaciones', models.TextField()),
                ('viernes_actividad', models.TextField()),
                ('viernes_dificultad', models.TextField()),
                ('viernes_apoyo', models.TextField()),
                ('viernes_observaciones', models.TextField()),
            ],
        ),
    ]
