# Generated by Django 5.0.6 on 2024-08-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0028_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('receptora', models.CharField(max_length=255)),
                ('tutor', models.CharField(max_length=255)),
                ('supervisor', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('tutor_receptora', models.CharField(max_length=255)),
                ('entidad2', models.CharField(max_length=255)),
                ('observaciones', models.TextField()),
                ('calificacion', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
