# Generated by Django 5.0.6 on 2024-08-15 23:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0029_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fecha_hora_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
