# Generated by Django 5.0.6 on 2024-08-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0030_visita_fecha_hora_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='estado',
            field=models.CharField(default='Espera', max_length=20),
        ),
    ]
