# Generated by Django 5.0.6 on 2024-08-31 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0031_evaluacion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('conclusiones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.empresa')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.evaluacion')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.perfil')),
            ],
        ),
    ]
