# Generated by Django 5.0.6 on 2024-09-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0032_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombres',
            field=models.CharField(default='', max_length=100),
        ),
    ]
