# Generated by Django 5.0.6 on 2024-09-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0035_reporte_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='reporte_estado',
            field=models.CharField(default='Espera', max_length=20),
        ),
    ]
