# Generated by Django 5.0.6 on 2024-09-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0037_remove_reporte_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='reporte_estado',
            field=models.CharField(default='Espera1', max_length=20),
        ),
    ]
