# Generated by Django 5.0.6 on 2024-09-05 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0041_cartaaceptacion_especializacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaaceptacion',
            name='formato',
        ),
    ]
