# Generated by Django 5.0.6 on 2024-09-06 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0042_remove_cartaaceptacion_formato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informediario',
            name='fecha_semanal',
        ),
        migrations.AddField(
            model_name='informediario',
            name='fecha_final',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='informediario',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
