# Generated by Django 5.0.6 on 2024-09-06 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0044_perfil_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='especializacion',
            field=models.CharField(default='Especializacion', max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='reporte_fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='perfil',
            name='reporte_numero',
            field=models.IntegerField(default=0),
        ),
    ]
