# Generated by Django 5.0.6 on 2024-09-06 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0045_perfil_especializacion_perfil_reporte_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='reporte_fecha_final',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
