# Generated by Django 5.0.6 on 2024-09-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0046_perfil_reporte_fecha_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
