# Generated by Django 5.0.6 on 2024-09-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0047_perfil_visitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaaceptacion',
            name='rector',
            field=models.CharField(default='Rector', max_length=100),
        ),
    ]
