# Generated by Django 5.0.6 on 2024-09-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0048_cartaaceptacion_rector'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='perfil',
            field=models.IntegerField(default=0),
        ),
    ]
