# Generated by Django 5.0.6 on 2024-09-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0049_evaluacion_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='fecha_finalizacion',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='fecha_inicio',
        ),
    ]
